export const INCREMENT_LIKES = "INCREMENT_LIKES";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const SEARCH_CHANGE = "SEARCH_CHANGE";
export const PROJECT_LIST_LOADING_SUCCESS = "START_LOADING_FINISH";
export const PROJECT_LIST_LOADING = "START_LOADING";

export const LOAD_USER_INFO = "LOAD_USER_INFO";
export const LOAD_USER_INFO_SUCCESS = "LOAD_USER_INFO_SUCCESS";

export const LOAD_PROJECT_DETAIL = "LOAD_PROJECT_DETAIL";
export const LOAD_PROJECT_DETAIL_SUCCESS =  "LOAD_PROJECT_DETAIL_SUCCESS";