export const INCREMENT_LIKES = "INCREMENT_LIKES";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const SEARCH_CHANGE = "SEARCH_CHANGE";
export const START_LOADING_FINISH = "START_LOADING_FINISH";
